---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-demo-cp-kubectl
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: hello
        image: '1'
        ports:
        - containerPort: 8080
